routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'Site\SiteController@index')->name('site');
Route::get('/appointment/success', 'Site\SiteController@appointmentSuccess')->name('site.appointment.success');


Route::get('/searchPanel', 'Site\SiteController@searchPanel')->name('site.searchPanel');
Route::get('/recommendPanel', 'Site\SiteController@recommendPanel')->name('site.recommendPanel');

Route::get('/productPanel', 'Site\SiteController@productPanel')->name('site.productPanel');
Route::get('/reservePanel', 'Site\SiteController@reservePanel')->name('site.reservePanel');



Auth::routes();

// AJAX Routes
Route::group(['middleware' => 'auth', 'prefix' => 'ajax', 'as' => 'ajax.'], function() {

    // Routes not blocked to Client Users
    Route::get('services', 'ServiceController@indexJson')->name('services.index');
    Route::get('services/{id}/times', 'ServiceController@availableTimes')->name('services.times');

    Route::post('appointments/client', 'AppointmentController@storeClientAppointment')->name('appointments.storeClientAppointment');

});

Route::group(['middleware' => 'auth', 'prefix' => 'home', 'as' => 'home.'], function() {

    // Routes Blocked to Client Users
    Route::group(['middleware' => 'block_client'], function() {
        Route::get('/', 'HomeController@index')->name('index');

        // Clients
        Route::resource('clients', 'ClientController');

        // Providers
        Route::resource('providers', 'ProviderController');

        // Services
        Route::resource('services', 'ServiceController');

        // Appointments
        Route::resource('appointments', 'AppointmentController');

        // Users
        Route::resource('users', 'UserController');

        // Settings
        Route::get('settings', 'SettingsController@index')->name('settings.index');
        Route::post('settings', 'SettingsController@store')->name('settings.store');
    });

});

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif
                    
                    <full-calendar :events="{{ $appointments }}" locale="en"></full-calendar>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            @if(Auth::user()->isProvider())
            <book-calendar provider="{{ Auth::user()->id }}" business-hours="{{ !$businessHours->isEmpty() ? $businessHours : 'false' }}" ref="book-calendar"></book-calendar>
            @else
            <book-calendar business-hours="{{ !$businessHours->isEmpty() ? $businessHours : 'false' }}" ref="book-calendar"></book-calendar>            
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/productPanel.blade.php
@extends('layouts.basic')

@section('content')
<div class="container">

    @auth
        @if(Auth::user()->isClient())


        @else
            <div class="row text-center" style="color: #FFFFFF; margin-bottom: 10px;">
                Hi, {{ Auth::user()->name }}
            </div>
            <div class="row text-center">
                <div class="col-sm-12">
                    <a href="{{ route('home.index') }}" class="btn btn-primary">Go to Admin Panel</a>
                </div>
            </div>    
        @endif
    @endauth

    @guest

    @endguest






    <div class="container-fluid">
        <div  style="background:#ffffff; border :1px solid #444444;"> 상품 리스트 </div>

        <div class="panel" style="height:500px;">
    @foreach($products as $product)
                <div class="col-md-3" style="background:#ffffff; text-align:center;">

                <h4>{{$product->brand}} {{$product->name}}</h4>
                    <img src ="{{$product->one_image}}" style="width:150px;"/>
                </div>

            @endforeach

            </div>
        </div>

</div>
@endsection

@section('scripts')
@include('js.config')
<script src="{{ mix('js/site.js') }}"></script>
@endsection

resources/views/recommendPanel.blade.php
@extends('layouts.basic')

@section('content')
<div class="container">


    @auth
        @if(Auth::user()->isClient())


        @else
            <div class="row text-center" style="color: #FFFFFF; margin-bottom: 10px;">
                Hi, {{ Auth::user()->name }}
            </div>

        @endif
    @endauth

    @guest

    @endguest



    <div class="container-fluid">
        <div  style="background:#ffffff; border :1px solid #444444;">메이크업 추천 해준다. </div>


        <div class="panel" style="height:500px;">
         추천 메이크업 검색
        </div>
    </div>

</div>
@endsection

@section('scripts')
@include('js.config')
<script src="{{ mix('js/site.js') }}"></script>
@endsection

resources/views/reservePanel.blade.php
@extends('layouts.basic')

@section('content')
<div class="container">
            
    @auth
        @if(Auth::user()->isClient())

            <div>hello client</div>

        @else
            <div class="row text-center" style="color: #FFFFFF; margin-bottom: 10px;">
                Hi, {{ Auth::user()->name }}
            </div>
            <div class="row text-center">
                <div class="col-sm-12">
                    <a href="{{ route('home.index') }}" class="btn btn-primary">Go to Admin Panel</a>
                </div>
            </div>    
        @endif
    @endauth

    @guest
    <div class="row text-center">
        <div class="col-sm-12">
            <a href="{{ route('login') }}" class="btn btn-primary" style="margin-top:10px;">취향 분석을 위해 로그인 해주세요.!</a>

        </div>

    </div>
    @endguest



    <div class="container-fluid">
        <div class="panel">
            <div class="panel-heading">
                <h3>Products</h3>
                <br>
                <div class="row">
                    <div class="col-sm-2">
                        @can('create-provider', LaraBooking\Models\User::class)
                            <a href="{{ route('home.providers.create') }}" class="btn btn-primary"> <i class="fa fa-plus"></i> Provider</a>
                        @endcan
                    </div>
                    <div class="col-sm-10">
                        <form action="">
                            <div class="input-group">
                                <input type="text" id="search" name="search" class="form-control" placeholder="Search..." value="">
                                <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Search</button>
                          </span>
                            </div>
                        </form>
                    </div>
                </div>

                <br>

            </div>


            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-stripped table-hover">
                        <thead>
                        <tr>
                            <th>브랜드</th>
                            <th>이름</th>
                            <th class="visible-md visible-lg">설명</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($products as $product)
                            <tr>
                                <td>  <img src ="{{$product->one_image}}" style="width:100px;"/> </td>
                                <td style="width:100px;"><a href="{{ route('home.providers.show', $product->id) }}" >{{ $product->brand }} {{ $product->name }}</a></td>
                                <td class="visible-md visible-lg">{{ $product->desc }}</td>


                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>

                {!! $products->render() !!}
            </div>




        </div>






    </div>




    <div>
        <div class="container" >
    @foreach($products as $product)
                <div class="col-md-3" style="background:#ffffff; text-align:center;">

                <h4>{{$product->brand}} {{$product->name}}</h4>
                    <img src ="{{$product->one_image}}" style="width:150px;"/>
                </div>

            @endforeach

            </div>
        </div>


    </div>
</div>
@endsection

@section('scripts')
@include('js.config')
<script src="{{ mix('js/site.js') }}"></script>
@endsection

resources/views/searchPanel.blade.php
@extends('layouts.basic')

@section('content')
<div class="container">
    <div> 검색 </div>

    @auth
        @if(Auth::user()->isClient())


        @else
            <div class="row text-center" style="color: #FFFFFF; margin-bottom: 10px;">
                Hi, {{ Auth::user()->name }}
            </div>
            <div class="row text-center">
                <div class="col-sm-12">
                    <a href="{{ route('home.index') }}" class="btn btn-primary">Go to Admin Panel</a>
                </div>
            </div>    
        @endif
    @endauth

    @guest

    @endguest



    <div class="container-fluid">
        <div class="panel">
            <div class="panel-heading">
                <h3>Products</h3>
                <br>
                <div class="row">
                    <div class="col-sm-2">
                        @can('create-provider', LaraBooking\Models\User::class)
                            <a href="{{ route('home.providers.create') }}" class="btn btn-primary"> <i class="fa fa-plus"></i> Provider</a>
                        @endcan
                    </div>
                    <div class="col-sm-10">
                        <form action="">
                            <div class="input-group">
                                <input type="text" id="search" name="search" class="form-control" placeholder="Search..." value="">
                                <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Search</button>
                          </span>
                            </div>
                        </form>
                    </div>
                </div>

                <br>

            </div>


            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-stripped table-hover">
                        <thead>
                        <tr>
                            <th>브랜드</th>
                            <th>이름</th>
                            <th class="visible-md visible-lg">설명</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($products as $product)
                            <tr>
                                <td>  <img src ="{{$product->one_image}}" style="width:100px;"/> </td>
                                <td style="width:100px;"><a href="{{ route('home.providers.show', $product->id) }}" >{{ $product->brand }} {{ $product->name }}</a></td>
                                <td class="visible-md visible-lg">{{ $product->desc }}</td>


                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>

                {!! $products->render() !!}
            </div>




        </div>






    </div>




    <div>
        <div class="container" >
    @foreach($products as $product)
                <div class="col-md-3" style="background:#ffffff; text-align:center;">

                <h4>{{$product->brand}} {{$product->name}}</h4>
                    <img src ="{{$product->one_image}}" style="width:150px;"/>
                </div>

            @endforeach

            </div>
        </div>


    </div>
</div>
@endsection

@section('scripts')
@include('js.config')
<script src="{{ mix('js/site.js') }}"></script>
@endsection

resources/views/site.blade.php
@extends('layouts.basic')

@section('content')
<div class="container">
            
    @auth
        @if(Auth::user()->isClient())
            <book-add-appointments></book-add-appointments>
        @else
            <div class="row text-center" style="color: #FFFFFF; margin-bottom: 10px;">
                Hi, {{ Auth::user()->name }}
            </div>
            <div class="row text-center">
                <div class="col-sm-12">
                    <a href="{{ route('home.index') }}" class="btn btn-primary">Go to Admin Panel</a>
                </div>
            </div>    
        @endif
    @endauth

    @guest


    <div class="row text-center">
        <div class="col-sm-12">
            <a href="{{ route('login') }}" class="btn btn-primary" style="margin-top:10px;">브랜드 제품 검색</a>
            <a href="{{ route('login') }}" class="btn btn-primary" style="margin-top:10px;">메이크업 예약하기</a>

        </div>

    </div>
    <div class ="row text-center">
    <div class="col-md-8" style ="padding-top:20px; ">
        <div class="embed-youtube" >
            <iframe  src="https://www.youtube.com/embed/HyJJRQ5SGQo" frameborder="0" gesture="media" allow="encrypted-media" allowfullscreen></iframe>
        </div>
    </div>
    </div>


    @endguest

</div>
@endsection

@section('scripts')
@include('js.config')
<script src="{{ mix('js/site.js') }}"></script>
@endsection